language: ruby
bundler_args: --without development
rvm:
- 2.0.0
- 1.9.3
- jruby
- rbx-19mode
gemfile:
- gemfiles/Gemfile.rails-3-1
- gemfiles/Gemfile.rails-3-2
- gemfiles/Gemfile.rails-4-0
services:
- rabbitmq
deploy:
  provider: rubygems
  api_key:
    secure: gNudZK0JaRRweudmkpdkJjUMydItTSW5cXjpYdYCfahqd/cD0xPjxotr2TCHrJibfVauoT/PytbQWcP3jnOYytp6oS0up5Y+uKpGmbqVYx/rZvShWALszcBs71lUh/IZpDXNHc+yo/01HCn10/uQUFRtrjWgMwHtHxXb09xE4wQ=
  gem: acfs
  on:
    branch: master
    repo: jgraichen/acfs
